---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  phan:
    enabled: true
    config:
      file_extensions: "php"
  phpcodesniffer:
    enabled: true
    config:
        standard: "PSR1,PSR2"
  phpmd:
    enabled: true
  radon:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.md"
  - "**.php"
  - "**.scss"
exclude_paths:
- config/
- public/css/
- public/js/
- resources/views/vendor/
- storage/
- tests/