language: php

php:
  - 7.0
  - 7.1
  - 7.2

services:
  - mysql
  - redis

branches:
    only: master

sudo: false

env:
  global:
    - setup=basic

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: setup=lowest
    - php: 7.0
      env: setup=stable
    - php: 7.1
      env: setup=lowest
    - php: 7.1
      env: setup=stable
    - php: 7.2
      env: setup=lowest
    - php: 7.2
      env: setup=stable

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 || $TRAVIS_PHP_VERSION != 7.2 ]] ; then phpenv config-rm xdebug.ini; fi
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis;'

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi
  - cp .env.example .env
  - travis_retry php artisan key:generate
  - travis_retry php artisan migrate --seed

script: vendor/bin/phpunit

addons:
  code_climate:
    repo_token: 1c22d320eac6bb9e839b58675b185ee26ddd4261e9dd827a99d826905628756d

cache:
  directories:
      - $HOME/.composer/cache